name: install_and_create_app
on:
  push:
    branches: main
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls | mkdir flutter | cd flutter | git clone -b stable https://github.com/flutter/flutter.git
      - run: export PATH="$PATH:`pwd`/flutter/bin"
      - run: flutter channel stable
      - run: flutter upgrade
      - run: flutter precache
      - run: flutter doctor
      - run: flutter create myapp
      - run: cd myapp
